### ISSUE TITLE
errorHandleMiddle模块的一些问题

### ISSUE THREAD

**Issue by alianrock** [jackhutu/jackblog-api-koa#10]
你好，最近在看你的项目，发现server/util/error/index.js下面对于err.errors的处理好像有点问题：
```
 if(err.errors && typeof(err.errors) === 'object'){
        _.mapValues(err.errors, (item)=>{
          if(item.message){
            error_msg = item.message     //这里这样的处理可能有错误，error_msg只会保存最后一个message
          }
        })
      }

```

是错误还是故意为之呢？

还有这个中间件如果是因为代码问题抛出的错误，并且没有对错误进行包装处理，是不是会直接把错误发送暴露给客户端呢？

**Comment by jackhutu** [comment]
没记错的话, 这样写是为了拿到mongo model 里面抛出的错误信息.  至于只保存最后一个message, 我觉得这没什么问题.  不过第二个问题, 确实是有这样的可能, 这里还需要改造一下.

**Comment by alianrock** [comment]
感谢回复，thx
