### ISSUE TITLE
一个关于您源码的问题有些看不懂，希望获得您的回答:)

### ISSUE THREAD

**Issue by xwpongithub** [jackhutu/jackblog-api-koa#11]
在auth.service.js这个文件里的isAuthenticated方法中，有这样一段，这个user._id是在什么时候传入的，我不是很明白，望作者解答：
![image](https://user-images.githubusercontent.com/11469225/28455202-c1d34926-6e30-11e7-961a-62c67efb362d.png)

比如，我在user.test.js中看到的me方法的调用并没有传入id，但这里调用时会执行isAuthenticated方法时必须要判断传过来的参数中是否有_id,如果这里的me方法没有传的话那又是从哪里传过来的这个_id值呢？
![c9z 0k4edlg44l6o0n64g](https://user-images.githubusercontent.com/11469225/28455626-466e0684-6e32-11e7-8ce1-ec73123a4710.png)

**Comment by jackhutu** [comment]
在生成token的时候就有了ctx.state.user, 而我在signToken时传入了_id, 默认就是ctx.state.user, 也可以不用user, 而自己指定其它名称,  你可以看看koa-jwt 以及jsonwebtoken的源码.

**Comment by xwpongithub** [comment]
谢谢您的回复~我明白了~koa-jwt的源码还是等我把您的代码完全看透了再去看下吧~循序渐进~

**Comment by jackhutu** [comment]
OK, 加油
