### ISSUE TITLE
关于七牛云存储的配置问题

### ISSUE THREAD

**Issue by xwpongithub** [jackhutu/jackblog-api-koa#12]
我自己申请了一个七牛云的账号，在运行您的上传图片的测试用例时发现上传成功了，但域名是七牛云分配的免费域名，是不是还要配置下镜像存储和绑定一下自己的域名，才能将存储后的路径图片路径通过这样：http://upload.jackhu.top/article/article/test.png 访问。
  而且关于这点我还有点不明白的就是这样以来的话我是不是要在自己配置好的那个域名下保存一份，在七牛这边再保存一份呢

**Comment by jackhutu** [comment]
在七牛那里配置使用自己的域名, 并根据七牛的提示配置自己的域名解析. 这样就可以使用自己的域名替换七牛免费的域名. 只需要传到七牛就可以了, 并不需要保存两份.
