### ISSUE TITLE
mac npm install 安装不了 报错

### ISSUE THREAD

**Issue by gejialun8888** [jackhutu/jackblog-api-koa#14]
WARN tar ENOENT: no such file or directory, open '/Users/rachelhao/Desktop/jackblog-api-koa-master/node_modules/.staging/nyc-102709d8/node_modules/core-js/library/fn/symbol/has-instance.js'
WARN tar ENOENT: no such file or directory, open '/Users/rachelhao/Desktop/jackblog-api-koa-master/node_modules/.staging/nyc-102709d8/node_modules/core-js/library/fn/symbol/to-string-tag.js'
WARN tar ENOENT: no such file or directory, open '/Users/rachelhao/Desktop/jackblog-api-koa-master/node_modules/.staging/nyc-102709d8/node_modules/core-js/library/fn/symbol/for.js'
WARN tar ENOENT: no such file or directory, open '/Users/rachelhao/Desktop/jackblog-api-koa-master/node_modules/.staging/nyc-102709d8/node_modules/core-js/library/fn/symbol/unscopables.js'
WARN tar ENOENT: no such file or directory, open '/Users/rachelhao/Desktop/jackblog-api-koa-master/node_modules/.staging/nyc-102709d8/node_modules/core-js/library/fn/symbol/observable.js'
npm ERR! Unexpected end of JSON input while parsing near '...transpiler":"^5.6.1",'

**Comment by hutuxuhui** [comment]
node版本大于7.6吗?

**Comment by gejialun8888** [comment]
v8.2.1

**Comment by hutuxuhui** [comment]
那应该不会呀, 我都试过了, 我的环境也是mac + node8.x.
