### ISSUE TITLE
在windows平台install会报错，错误出在安装koa-redis库的时候

### ISSUE THREAD

**Issue by SmokingIce** [jackhutu/jackblog-api-koa#16]
当安装koa-redis时，会要求安装hiredis，此时会抛出以下错误

> hiredis@0.5.0 install E:\Study\前端\blog\jackblog\jackblog-api-koa\node_modules\hiredis
> node-gyp rebuild
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.

按要求安装Python后（装的是Python2.7版本），又会抛出C++相关的错误。

请问在windows下，是否有办法成功 install koa-redis ？

**Comment by hutuxuhui** [comment]
我在这个https://github.com/jackhutu/jackblog-api-express 里面有关于windows的说明
