### ISSUE TITLE
你这个叫restful风格。。。大哥你开玩笑把。。。

### ISSUE THREAD

**Issue by leyue** [jackhutu/jackblog-api-koa#18]
router.get('/getUserList', auth.hasRole('admin'),controller.getUserList)
router.post('/addUser', auth.hasRole('admin'),controller.addUser)
这是restful。。。

**Comment by hutuxuhui** [comment]
请指教, 怎么样才是

**Comment by hutuxuhui** [comment]
确实是有些问题,  以后有空再修正一下.
