### ISSUE TITLE
调试问题

### ISSUE THREAD

**Issue by mlyknown** [jackhutu/jackblog-api-koa#3]
项目怎么下断点调试的啊，为什么我使用node-inspector 启动app.js，不能启动。。直接 node app.js就可以。

**Comment by mlyknown** [comment]
大湿用过这个调试工具没 https://github.com/Jam3/devtool。 也不能启动。。

**Comment by mlyknown** [comment]
这个问题是ccap 那个包的引起的，暂时不知道什么原因。
七牛云配置那个。因为我没有域名，好想就不能实名认证了，就不能使用了吗？

**Comment by jackhutu** [comment]
ccap安装好了吗, 那是验证码的包, 七牛有没有域名都可以使用的吧. 不配置七牛也是可以正常运行的. 只是后台管理部分功能没办法用.

**Comment by mlyknown** [comment]
不配置七牛，上传图片那里不能使用啊。。 可是我想一下完整的，我配置了    app_key
    app_secret   bucket:''       没有配置 domain，还是不能使用，因为我没有自己的域名，就不能使用七牛了吗？

**Comment by mlyknown** [comment]
为嘛关了啊 0.0.0

**Comment by jackhutu** [comment]
关错了 :)

**Comment by mlyknown** [comment]
0.0   大湿可否留个联系方式。。

**Comment by jackhutu** [comment]
这个domain 是指的你七牛配置里面的七牛域名, 如果自定义了域名,就是自己的域名, 你看七牛配置域名那里.  并不是非要你自己的域名的. 如: 7xkmsi.com2.z0.glb.qiniucdn.com

**Comment by mlyknown** [comment]
其实我今天这样子配置了的，可能也许是配置没生效，我在调试看看。。。 
大湿要不要建个organization，就弄个博客的各种框架实现什么的。主要我想弄个vue实现的admin,也可以贡献哈，我觉得admin那部分应该和客户端合在一起的。。。0.0

**Comment by jackhutu** [comment]
弄个organization也可以啊, 最开始的第一版是全部整在一起的https://github.com/jackhutu/jackblog-express-angular . 后来想简单些就去掉后台管理, 毕尽弄多了, 维护需要精力.

**Comment by mlyknown** [comment]
大湿,留个联系。我们一起弄嘛，就做一个开源博客。我想好好弄点开源的东西。。我可以写vue那块，还有node。。

**Comment by jackhutu** [comment]
你QQ多少, 我加你

**Comment by mlyknown** [comment]
q: 1053101033
