### ISSUE TITLE
程序运行不起来呀

### ISSUE THREAD

**Issue by gdhzkk** [jackhutu/jackblog-api-koa#4]
建议添加详细安装说明吧，小白不太懂，
请问win本地测试为什么还要安装Python 2.7，Microsoft Visual Studio C++ 2013呢？
我测试其他nodejs程序都不需要安装这么多呀？

**Comment by jackhutu** [comment]
具体要看你安装什么包, 如果你安装的包是使用了c++扩展, 就需要c++编译环境.  比如node-sass, ccap等等.
