### ISSUE TITLE
很喜欢你的程序，但要安装的东西太多了，能简化些吗？

### ISSUE THREAD

**Issue by gdhzkk** [jackhutu/jackblog-api-koa#6]
很喜欢你的程序，但要安装的东西太多了，小白好不容易都安装上了，结果cmd里还是大段的错误，能简化些吗？  使用门槛太高了呀
另外redis 有win32版本的

**Comment by jackhutu** [comment]
没多少要安装的东西, 都是经常用的到的呀,  cmd里安装有错误的话,  那环境可能没搭好, window看我写的注意事项. redis 官方没有windows版, 第三方提供的只有64位的.

**Comment by gdhzkk** [comment]
@jackhutu  我在网上下载的redis是win32版本的

**Comment by jackhutu** [comment]
项目主页上有redis下载链接,  是win64位的.  这项目是以学习为主, 尽量包含多的东西的.
----- 原始邮件 -----
发件人：gdhzkk <notifications@github.com>
收件人：jackhutu/jackblog-api-koa <jackblog-api-koa@noreply.github.com>
抄送人：Jack Hu <hutufeia2009@sina.com>,  Mention <mention@noreply.github.com>
主题：Re:_[jackhutu/jackblog-api-koa]_很喜欢你的程序，但要安装的东西太多了，能简化些吗？_(#6)
日期：2016年05月15日 22点38分

@jackhutu  我在网上下载的redis是win32版本的

&mdash;

**Comment by mlyknown** [comment]
~~~~~~
