### ISSUE TITLE
想问下 Docker镜像下载之后怎么跑起来.

### ISSUE THREAD

**Issue by yay2008** [jackhutu/jackblog-api-koa#8]
~$ sudo docker run -d -p 8800:7879 --name=blog jackhu/jenkins-deploy-nodejs:6   这样试了不行

**Comment by jackhutu** [comment]
是的, 这不是部署上线后的docker镜像,是这个registry.cn-hangzhou.aliyuncs.com/hutu/jackblog-api-koa-deploy, 端口是8800, 过会我会传到官方镜像仓库
